/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './route/__root'
import { Route as RegisterRouteImport } from './route/register'
import { Route as Recover_passwordRouteImport } from './route/recover_password'
import { Route as LoginRouteImport } from './route/login'
import { Route as GuardRouteImport } from './route/guard'
import { Route as IndexRouteImport } from './route/index'
import { Route as DashboardIndexRouteImport } from './route/dashboard/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Recover_passwordRoute = Recover_passwordRouteImport.update({
  id: '/recover_password',
  path: '/recover_password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardRoute = GuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guard': typeof GuardRoute
  '/login': typeof LoginRoute
  '/recover_password': typeof Recover_passwordRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guard': typeof GuardRoute
  '/login': typeof LoginRoute
  '/recover_password': typeof Recover_passwordRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guard': typeof GuardRoute
  '/login': typeof LoginRoute
  '/recover_password': typeof Recover_passwordRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guard'
    | '/login'
    | '/recover_password'
    | '/register'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guard'
    | '/login'
    | '/recover_password'
    | '/register'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/guard'
    | '/login'
    | '/recover_password'
    | '/register'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuardRoute: typeof GuardRoute
  LoginRoute: typeof LoginRoute
  Recover_passwordRoute: typeof Recover_passwordRoute
  RegisterRoute: typeof RegisterRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover_password': {
      id: '/recover_password'
      path: '/recover_password'
      fullPath: '/recover_password'
      preLoaderRoute: typeof Recover_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard': {
      id: '/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof GuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuardRoute: GuardRoute,
  LoginRoute: LoginRoute,
  Recover_passwordRoute: Recover_passwordRoute,
  RegisterRoute: RegisterRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
